Test
RePreus/Generator pull request #1
Opened 2019-07-29 19:34 UTC by RePreus

2019-07-29 19:43 UTC, Kenstin requested changes

2019-07-29 19:43 UTC, Kenstin commented on Generator.Application/Validations/PayloadValidator.cs
> +            RuleFor(p => p).Must(p => p.UserChoice == p.PictureA || p.UserChoice == p.PictureB)
to jest business logic, nie walidacja

2019-07-29 19:43 UTC, Kenstin commented on Generator.Application/Validations/PayloadValidator.cs
> +            RuleFor(p => p.PictureA.ToString()).Length(36).Must(p => p[8] == '-' && p[13] == '-' && p[18] == '-' && p[23] == '-');
to tu nie powinno być. asp net core samemu da radę zbindowac coś do Guidu, nie musisz mu dawac stringu. Jeśli nie bedzie w stanie zrobic binda do Guid, wtedy wyjebie model state invalid => w [ApiController] wywali się automatycznie 400 Bad Request

2019-07-29 19:43 UTC, Kenstin commented on Generator.Application/DTOs/PayloadDto.cs
> +        public PayloadDto(string pictureA, string pictureB, string userchoice)
po co ten constructor?

2019-07-29 19:44 UTC, Kenstin commented on Generator.Application/Validations/PayloadValidator.cs
> +            RuleFor(p => p.PictureA.ToString()).Length(36).Must(p => p[8] == '-' && p[13] == '-' && p[18] == '-' && p[23] == '-');
nvm, usunales juz

2019-07-29 19:46 UTC, Kenstin commented on Generator.Application/Validations/PayloadValidator.cs
> +            RuleFor(p => p).Must(p => p.UserChoice == p.PictureA || p.UserChoice == p.PictureB)
mam na myśli `RuleFor(p => p).Must(p => p.UserChoice == p.PictureA || p.UserChoice == p.PictureB)`, NotEmpty() jest jak najbardziej w porzakdu

2019-07-29 19:49 UTC, Kenstin commented
review + zmien nazwy payload na cos lepszego + pamietaj, ze autoryzacja nie bedzie w handlerze

2019-07-29 19:57 UTC, RePreus commented on Generator.Application/DTOs/PayloadDto.cs
> +        public PayloadDto(string pictureA, string pictureB, string userchoice)
dobra widzę

2019-07-29 19:59 UTC, RePreus commented
got it chief

2019-07-30 16:45 UTC, Kenstin requested changes

2019-07-30 16:45 UTC, Kenstin commented on Generator.Application/Handlers/PayloadHandler.cs
> -    public class PayloadHandler : IRequestHandler<PayloadDto, RequestResult>
PayloadHandler na ChoiceHandler

2019-07-30 16:45 UTC, Kenstin commented on Generator.Application/Validations/PayloadValidator.cs
> -    public class PayloadValidator : AbstractValidator<PayloadDto>
PayloadValidator na ChoiceDtoValidator

2019-07-30 17:17 UTC, Kenstin requested changes

2019-07-30 17:17 UTC, Kenstin commented on Generator.API/Controllers/ChoiceController.cs
> +using Microsoft.AspNetCore.Http;
niepotrzebne using

2019-07-30 17:17 UTC, Kenstin commented on Generator.API/Controllers/ChoiceController.cs
> +        public IActionResult Get()
po co ten Get istnieje?

2019-07-30 17:17 UTC, Kenstin commented on Generator.API/Program.cs
> +﻿using Generator.Application;
niepotrzebny using

2019-07-30 17:17 UTC, Kenstin commented on Generator.API/Startup.cs
> +            services.AddAuthentication(CookieAuthenticationDefaults.AuthenticationScheme)
po co authentication ciasteczkami? Bedziesz mial jwt przeciez

2019-07-30 17:17 UTC, Kenstin commented on Generator.Application/Handlers/ChoiceHandler.cs
> +            if (choiceDto.PictureA != choiceDto.UserChoice && choiceDto.PictureB != choiceDto.UserChoice)
```suggestion
           if (choiceDto.UserChoice != choiceDto.PictureA && choiceDto.UserChoice != choiceDto.PictureB)
```

2019-07-30 17:17 UTC, Kenstin commented on Generator.Application/Models/RequestResult.cs
> +using System.Net;
niepotrzebne usingi

2019-07-30 17:17 UTC, Kenstin commented on Generator.Application/Models/RequestResult.cs
> +            this.Message = new List<string>();
```suggestion
            Message = new List<string> { message };
```

2019-07-30 17:17 UTC, Kenstin commented on Generator.Application/Models/RequestResult.cs
> +            this.Success = success;
Wszystkie te this. sa niepotrzebne

2019-07-30 17:17 UTC, Kenstin commented on Generator.Application/Models/RequestResult.cs
> +        public bool Success { get; set; }
czy to musi miec publiczny setter?

2019-07-30 17:17 UTC, Kenstin commented on Generator.Application/Models/RequestResult.cs
> +        public List<string> Message { get; set; }
czy to musi miec publiczny setter?

2019-07-30 17:17 UTC, Kenstin commented on Generator.Application/Validations/ValidationBehaviour.cs
> +﻿using System.Linq;
niepotrzebne using

2019-07-30 17:17 UTC, Kenstin commented on Generator.Domain/Choice.cs
> +        public Guid PictureA { get; set; }
czy to musi wszystko miec publiczne settery? Moze ustawic bez settera i ustawiac to w konstruktorze?

2019-07-30 17:40 UTC, Kenstin requested changes

2019-07-30 17:40 UTC, Kenstin commented on Generator.Application/Models/RequestResult.cs
> +        public bool Success { get; private set; }
private set; jest tu niepotrzebne

2019-07-30 17:40 UTC, Kenstin commented on Generator.Domain/Choice.cs
> +        public Guid PictureA { get; private set; }
private set; sa niepotzrebne

2019-07-30 17:45 UTC, Kenstin requested changes

2019-07-30 17:45 UTC, Kenstin commented on Generator.Application/Models/RequestResult.cs
> +        public RequestResult(List<string> message = null, bool success = true)
pamietaj, ze zawsze powinienes prosić o jak najmniej concrete type, w tym wypadku nei potrzebujesz cech Listy, wystarcczy Ci IEnumerable. A nawet jesli potrzebowalbys indexux, to zażądaj ICollection albo chociaż IList

2019-07-30 17:45 UTC, Kenstin commented on Generator.Application/Models/RequestResult.cs
> +            Success = success;
kod w konstruktorach sie troche powtarza, spróbuj je napisać, by jeden korzystał z drugiego, wykorzystując `: this(args)`

2019-07-30 18:37 UTC, Kenstin approved these changes

2019-07-30 18:40 UTC, merged