EF Core etc
RePreus/Generator pull request #2
Opened 2019-08-17 15:50 UTC by RePreus

- Renamed controller
- Added exception handler
- EF Core
- Payload and PayloadHandler
- SaveToFile Extension method
- Minor changed to ChoiceHandler
- New Validation rules

2019-08-26 18:45 UTC, Kenstin commented on Generator.API/Controllers/GeneratorController.cs
> +        public async Task<ActionResult<Payload>> Get([FromBody] ReceivedName tableName)
to nie jest restful

2019-08-26 18:45 UTC, Kenstin commented on Generator.API/Controllers/GeneratorController.cs
> +        public async Task<ActionResult<Payload>> Get([FromBody] ReceivedName tableName)
/api/generator/{tuwpisujeszname}

2019-08-26 18:53 UTC, Kenstin commented on Generator.Application/Handlers/PayloadHandler.cs
> +        public static Tuple<int, int> GetRandomIds(int range)
moze byc private

2019-08-26 18:54 UTC, Kenstin commented on Generator.Domain/Picture.cs
> +        public string Image { get; }
primitive obsession

2019-08-26 18:56 UTC, Kenstin commented on Generator.Infrastructure/IO/FileWriter.cs
> +        private const string Filename = "Choices.csv";
xD

2019-08-28 17:52 UTC, Kenstin requested changes

2019-08-28 17:52 UTC, Kenstin commented on Generator.API/Generator.API.csproj
> +    <None Include="app.config" />
co to

2019-08-28 17:52 UTC, Kenstin commented on Generator.API/Startup.cs
> +            services.AddSingleton<IWriter, FileWriter>();
singleton?

2019-08-28 17:52 UTC, Kenstin commented on Generator.API/app.config
> +﻿<?xml version="1.0" encoding="utf-8" ?>
appsettings.json a nie jakies app.config w xml XD

2019-08-28 17:52 UTC, Kenstin commented on Generator.Domain/Picture.cs
> +    public class Picture
zrób sobie klase bazowa do Entity

2019-08-28 17:52 UTC, Kenstin commented on Generator.Infrastructure/IO/FileWriter.cs
> +        public void Save(string[] pictures, Domain.Choice choice)
IEnumerable a nie array

2019-08-28 17:52 UTC, Kenstin commented on Generator.Infrastructure/IO/FileWriter.cs
> +    public class FileWriter : IWriter
zmienilbym nazwy, by bylo wyraznie widac, ze to writer i IWriter do zapisywania choice i picture

2019-08-28 17:52 UTC, Kenstin commented on Generator.Infrastructure/IO/FileWriter.cs
> +            filename = ConfigurationManager.AppSettings["filename"] ?? "DefaultFilename.csv";
moim zdaniem to nei jest dobre rozwiazanie, ograniczasz sie do jednego pliku

2019-08-28 17:52 UTC, Kenstin commented on Generator.Infrastructure/IO/FileWriter.cs
> +        }
nie musisz zamknac pliku do ktorego zapisujesz?

2019-08-28 17:52 UTC, Kenstin commented on Generator.Infrastructure/IO/FileWriter.cs
> +            using (StreamWriter outputFile = File.AppendText(filename))
nwaet jesli plik sie sam zamyka, to otwieranie go i zamykanie w kolko po 500 razy jest dość nieefektywne, tym bardziej, ze kazdy przecinek i tak dalej to nowe otwarcie/zamkniecie pliku

2019-08-28 17:52 UTC, Kenstin commented on Generator.Domain/Choice.cs
> -        public Choice(Guid pictureA, Guid pictureB, Guid userChoice)
nie chcesz jednak zostawić guid?

2019-08-28 17:52 UTC, Kenstin commented on Generator.Application/Interfaces/IWriter.cs
> +        void Save(string[] pictures, Domain.Choice choice);
moze async?

2019-08-28 17:52 UTC, Kenstin commented on Generator.Application/Models/ReceivedName.cs
> +    public class ReceivedName : IRequest<Payload>
commands mediatora nazywa się CostamCommand, a handler CosTamCommandHandler

2019-08-28 17:52 UTC, Kenstin commented on Generator.Application/Models/Payload.cs
> +    public class Payload
payload czego?

2019-08-28 17:52 UTC, Kenstin commented on Generator.Application/Validations/ChoiceDtoValidator.cs
> +            RuleFor(p => p.PictureAId).NotEmpty().GreaterThan(0);
notempty jest chyba niepotrzebne przy greater than 0

2019-08-28 17:52 UTC, Kenstin commented on Generator.Application/Handlers/PayloadHandler.cs
> +            var pictures = context.Pictures.OrderBy(r => Guid.NewGuid()).Take(2).ToArray();
ToArray() xD?
a btw - nie ma orderby async lub cos w tym stylu? jakos to async zrobic

2019-08-28 17:52 UTC, Kenstin commented on Generator.Application/Handlers/ChoiceHandler.cs
> +    public class ChoiceHandler : AsyncRequestHandler<ChoiceDto>
to samo, zle nazewnictwo

2019-08-28 17:52 UTC, Kenstin commented on Generator.Application/Handlers/ChoiceHandler.cs
> +            string[] pictures = { context.Pictures.Find(choice.PictureAId).Image, context.Pictures.Find(choice.PictureBId).Image };
array?

2019-08-28 17:53 UTC, Kenstin commented on Generator.API/Startup.cs
> +            services.AddSingleton<IWriter, FileWriter>();
+ tamta reszta moze byc jak na moje scoped

2019-09-22 17:04 UTC, Kenstin requested changes

2019-09-22 17:04 UTC, Kenstin commented on Generator.Infrastructure/Configuration/ChoiceWriterConfiguration.cs
> +        public string filename { get; set; }
niezły lowercas

2019-09-22 17:04 UTC, Kenstin commented on Generator.API/Controllers/GeneratorController.cs
> +        [HttpPost("response")]
nie podoba mi sie nazwa tego endpoitu, teog nizej tez

2019-09-22 17:04 UTC, Kenstin commented on Generator.Application/Commands/ChoiceCommand.cs
> +    public class ChoiceCommand : IRequest
jesli to dto to niech sie konczy na Dto

2019-09-22 17:04 UTC, Kenstin commented on Generator.API/Startup.cs
> +            services.AddScoped<IValidator<ReceivedNameQuery>, ReceivedNameValidator>();
po nazwie niezbyt rozumiem co robi "received name" query

2019-09-22 17:04 UTC, Kenstin commented on Generator.Application/Handlers/ReceivedNameQueryHandler.cs
> +            return Task.FromResult(new PicturesPayload(pictures[0].Id, pictures[0].Image, pictures[1].Id, pictures[1].Image));
co to pictures payload?

2019-09-22 17:04 UTC, Kenstin commented on Generator.Application/Mapping/MappingProfile.cs
> +            CreateMap<ChoiceCommand, Choice>();
czemu mappujesz command na domain?

2019-09-22 17:04 UTC, Kenstin commented on Generator.Application/Queries/ReceivedNameQuery.cs
> +    public class ReceivedNameQuery : IRequest<PicturesPayload>
pisalem co do tej nazwy juz wyzej, ale tak dla pewnosci napisze dwa razy

2019-09-22 17:04 UTC, Kenstin commented on Generator.Domain/Entities/Choice.cs
> +        public string PictureA { get; set; }
dalej nie wiem czy trzymanie tego w stringu i w taki sposob jest dobrym pomyslem

2019-09-22 17:04 UTC, Kenstin commented on Generator.Domain/Entities/Choice.cs
> +        public string PictureA { get; set; }
i w sumie jesli to jest entity od wyboru to po co on przechowuje obrazek?

2019-09-22 17:04 UTC, Kenstin commented on Generator.Infrastructure/IO/ChoiceWriter.cs
> +            await outputFile.WriteAsync(properties[properties.Length - 1] + System.Environment.NewLine);
a streamwriter to sie sam zdisposuje?

2019-09-22 17:12 UTC, RePreus commented on Generator.Infrastructure/IO/ChoiceWriter.cs
> +            await outputFile.WriteAsync(properties[properties.Length - 1] + System.Environment.NewLine);
Tak

2019-09-22 17:34 UTC, Kenstin commented on Generator.Infrastructure/IO/ChoiceWriter.cs
> +            await outputFile.WriteAsync(properties[properties.Length - 1] + System.Environment.NewLine);
ale kozak
to ten nowy c# 8.0?

2019-09-25 17:47 UTC, Kenstin requested changes

2019-09-25 17:47 UTC, Kenstin commented on Generator.API/Controllers/GeneratorController.cs
> +        public async Task<IActionResult> Post([FromBody] SaveChosenPicturesCommand request)
[FromBody] jest niepotrzebne przy apicontrollerze

2019-09-25 17:47 UTC, Kenstin commented on Generator.API/Controllers/GeneratorController.cs
> +    public class GeneratorController : ControllerBase
controller moze byc pictures to wtedy w tych action nie musialbys powtarzac tego samego

2019-09-25 17:47 UTC, Kenstin commented on Generator.API/Controllers/GeneratorController.cs
> +        public async Task<ActionResult<RandomPicturesResponseDto>> Get([FromBody] GetRandomPicturesQuery receivedName)
receivedName to chujowa nazwa

2019-09-25 17:47 UTC, Kenstin commented on Generator.API/Generator.API.csproj
> +    <Compile Remove="wwwroot\**" />
o kurwa XD

2019-09-25 17:47 UTC, Kenstin commented on Generator.Application/Dtos/RandomPicturesResponseDto.cs
> +        public Picture PictureA { get; }
czemu dto ma entity w sobie

2019-09-25 17:47 UTC, Kenstin commented on Generator.Application/Queries/GetRandomPicturesQuery.cs
> +        public string Name { get; set; }
name czego

2019-09-25 17:47 UTC, Kenstin commented on Generator.Application/Validations/ChoiceCommandValidator.cs
> +        public ChoiceCommandValidator()
nazwe zmien

2019-09-25 17:47 UTC, Kenstin commented on Generator.Application/Validations/ReceivedNameValidator.cs
> +        public ReceivedNameValidator()
nazwe zmein

2019-09-27 16:05 UTC, Kenstin approved these changes

2019-10-05 11:07 UTC, merged